export const AIRPORT_LITS = [
    {
      id:1,
      city:'Jakarta',
      country:'Indonesia',
      name:'Juanda',
      code:'JKTA'
    },
    {
      id:2,
      city:'Balikpapan',
      country:'Indonesia',
      name:'Sepinggan',
      code:'BPN'
    },
    {
      id:3,
      city:'Bali',
      country:'Indonesia',
      name:'Ngurah Rai International Airport',
      code:'DPS'
    },
    {
      id:4,
      city:'Surabaya',
      country:'Indonesia',
      name:'Juanda',
      code:'SUB'
    }
  ]